
deployment:
  image:  
    repository: quay.io/fiware/waltid
    tag: 1.14.0-SNAPSHOT
    pullPolicy: Always
api:
  core: 
    enabled: true
  auditor: 
    enabled: true
  signatory: 
    enabled: true
  custodian: 
    enabled: true
  essif: 
    enabled: true

persistence: 
  enabled: false
  pvc:
    size: 1Gi

templates:
  BatteryPassAuthCredential.json: |
    {
      "@context": ["https://www.w3.org/2018/credentials/v1"],
      "credentialSchema": {
        "id": "https://raw.githubusercontent.com/FIWARE-Ops/batterypass-demonstrator/main/docs/schema.json",
        "type": "FullJsonSchemaValidator2021"
      },
      "credentialSubject": {
        "familyName": "Happy",
        "firstName": "User",
        "roles": [{
          "names": ["P.Info.gold"],
          "target": "did:elsi:target"
        }]
      },
      "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b5",
      "issued": "2021-08-31T00:00:00Z",
      "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
      "validFrom": "2021-08-31T00:00:00Z",
      "issuanceDate": "2021-08-31T00:00:00Z",
      "type": ["VerifiableCredential", "BatteryPassAuthCredential"]
    }
  PacketDeliveryService.json: |
    {
      "@context": ["https://www.w3.org/2018/credentials/v1"],
      "credentialSchema": {
        "id": "https://raw.githubusercontent.com/hesusruiz/dsbamvf/main/schemas/PacketDeliveryService/2022-10/schema.json",
        "type": "FullJsonSchemaValidator2021"
      },
      "credentialSubject": {
        "familyName": "Ruiz",
        "firstName": "Jesus",
        "id": "did:ebsi:2AEMAqXWKYMu1JHPAgGcga4dxu7ThgfgN95VyJBJGZbSJUtp",
        "roles": [{
          "names": ["P.Info.gold"],
          "target": "did:elsi:packetdelivery"
        }]
      },
      "id": "urn:uuid:3add94f4-28ec-42a1-8704-4e4aa51006b4",
      "issued": "2021-08-31T00:00:00Z",
      "issuer": "did:ebsi:2A9BZ9SUe6BatacSpvs1V5CdjHvLpQ7bEsi2Jb6LdHKnQxaN",
      "validFrom": "2021-08-31T00:00:00Z",
      "issuanceDate": "2021-08-31T00:00:00Z",
      "type": ["VerifiableCredential", "PacketDeliveryService"]
    }